server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://rc4-pedro-server-db.cuupyzlcppur.ap-northeast-2.rds.amazonaws.com/rasingcamp4?useSSL=false&autoReconnect=true # 변경해주세요
    username:  pedro # 변경해주세요
    password: GUStjr1085! # 변경해주세요
    #driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    driver-class-name: com.mysql.jdbc.Driver # mysql 5버전